In [3]:
import pandas as pd
df = pd.read_csv("md_voter_file.txt", sep='\t', on_bad_lines='skip') 
df.head()

C:\Users\Geoffrey\AppData\Local\Temp\ipykernel_18276\268250529.py:2: DtypeWarning: Columns (0,5,6,7,10,13,21,22,27,28,30,31,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("md_voter_file.txt", sep='\t', on_bad_lines='skip')

,VTR_ID,LastName,FirstName,MiddleName,Suffix,HouseNumber,HouseSuffix,StreetPreDirection,StreetName,StreetType,...,BirthDate,CountyRegistrationDate,StateRegistrationDate,11/08/2016-PG,06/02/2020-PP,11/03/2020-PG,05/14/2024-PP,11/05/2024-PG,County,Unnamed: 44
0,500696252,LANTZ,BETHANY,BROOKE,NaN,5.0,NaN,NaN,OAKLAWN,AVE,...,08/20/1991,08/20/2012,08/20/2012,NaN,2020 PRESIDENTIAL PRIMARY ELECTION,2020 PRESIDENTIAL GENERAL ELECTION,NaN,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN
1,3596552,TRUE,WANDA,HARRIS,NaN,11800.0,NaN,NaN,GREEN RIDGE,RD,...,10/10/1954,09/16/1980,09/16/1980,2016 PRESIDENTIAL GENERAL ELECTION,2020 PRESIDENTIAL PRIMARY ELECTION,2020 PRESIDENTIAL GENERAL ELECTION,2024 PRESIDENTIAL PRIMARY ELECTION,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN
2,501592474,CUTTER,ALISON,MARIE,NaN,11616.0,NaN,NaN,POPLAR,AVE,...,09/10/2000,03/10/2017,03/10/2017,NaN,NaN,NaN,2024 PRESIDENTIAL PRIMARY ELECTION,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN
3,3635319,AKE,DAVID,ALEXANDER,NaN,519.0,NaN,NaN,MARYLAND,ST,...,02/11/1985,02/07/2019,02/07/2019,NaN,NaN,NaN,2024 PRESIDENTIAL PRIMARY ELECTION,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN
4,4343788,PRITCHARD,NANCY,ADAMS,NaN,15.0,NaN,NaN,FOREST,DR,...,09/04/1959,07/07/2020,10/08/1984,2016 PRESIDENTIAL GENERAL ELECTION,NaN,2020 PRESIDENTIAL GENERAL ELECTION,NaN,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN

In [4]:
df.columns

Index(['VTR_ID', 'LastName', 'FirstName', 'MiddleName', 'Suffix',
       'HouseNumber', 'HouseSuffix', 'StreetPreDirection', 'StreetName',
       'StreetType', 'StreetPostDirection', 'UnitType', 'UnitNumber',
       'NonStandardAddress', 'ResidentialCity', 'ResidentialState',
       'ResidentialZip', 'ResidentialZipPlus', 'MAILINGADDRESS', 'MAILINGCITY',
       'MAILINGSTATE', 'MAILINGZIP', 'MAILINGZIPPLUS', 'StatusCode', 'Party',
       'Gender', 'Congressional', 'Legislative', 'Councilmanic',
       'Commissioner', 'Ward', 'Municipal', 'School', 'Precinct', 'Split',
       'BirthDate', 'CountyRegistrationDate', 'StateRegistrationDate',
       '11/08/2016-PG', '06/02/2020-PP', '11/03/2020-PG', '05/14/2024-PP',
       '11/05/2024-PG', 'County', 'Unnamed: 44'],
      dtype='object')

In [20]:
from datetime import date
from datetime import datetime
# coded based on https://www.geeksforgeeks.org/python-program-to-calculate-age-in-year/

def calculateAge(birthDate):
    today = date.today()
    age = today.year - birthDate.year - ((today.month, today.day) <(birthDate.month, birthDate.day))
    return age

In [21]:
import warnings
warnings.filterwarnings('ignore')
df["BirthDate"] = pd.to_datetime(df["BirthDate"], format="%m/%d/%Y")
df['age'] = df['BirthDate'].apply(calculateAge)

In [23]:
df['age_bracket'] = df['age'].apply(lambda x: 
    "18-24" if x <= 24 else 
    "25-34" if x <= 34 else 
    "35-50" if x <= 50 else 
    "51-64" if x <= 64 else 
    "65+")

In [24]:
df.head()

,VTR_ID,LastName,FirstName,MiddleName,Suffix,HouseNumber,HouseSuffix,StreetPreDirection,StreetName,StreetType,...,StateRegistrationDate,11/08/2016-PG,06/02/2020-PP,11/03/2020-PG,05/14/2024-PP,11/05/2024-PG,County,Unnamed: 44,age,age_bracket
0,500696252,LANTZ,BETHANY,BROOKE,NaN,5.0,NaN,NaN,OAKLAWN,AVE,...,08/20/2012,NaN,2020 PRESIDENTIAL PRIMARY ELECTION,2020 PRESIDENTIAL GENERAL ELECTION,NaN,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN,33.0,25-34
1,3596552,TRUE,WANDA,HARRIS,NaN,11800.0,NaN,NaN,GREEN RIDGE,RD,...,09/16/1980,2016 PRESIDENTIAL GENERAL ELECTION,2020 PRESIDENTIAL PRIMARY ELECTION,2020 PRESIDENTIAL GENERAL ELECTION,2024 PRESIDENTIAL PRIMARY ELECTION,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN,70.0,65+
2,501592474,CUTTER,ALISON,MARIE,NaN,11616.0,NaN,NaN,POPLAR,AVE,...,03/10/2017,NaN,NaN,NaN,2024 PRESIDENTIAL PRIMARY ELECTION,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN,24.0,18-24
3,3635319,AKE,DAVID,ALEXANDER,NaN,519.0,NaN,NaN,MARYLAND,ST,...,02/07/2019,NaN,NaN,NaN,2024 PRESIDENTIAL PRIMARY ELECTION,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN,40.0,35-50
4,4343788,PRITCHARD,NANCY,ADAMS,NaN,15.0,NaN,NaN,FOREST,DR,...,10/08/1984,2016 PRESIDENTIAL GENERAL ELECTION,NaN,2020 PRESIDENTIAL GENERAL ELECTION,NaN,2024 PRESIDENTIAL GENERAL ELECTION,Allegany,NaN,65.0,65+

In [30]:
df.columns
replacements = {key: 'OTH' for key in [
    'ONLM', 'OIN', 'OWCP', 'OLB', 'GRN',
    'OBAR', 'OSC', 'OCH', 'OPAT', 'ORE',
    'OCON', 'OSD', 'OFCH', 'OLIR', 'OCN',
    'OCS', 'OAM', 'OTP', 'OCO', 'OAL',
    'OAI', 'OPOP', 'ORL', 'OWO', 'OBM',
    'ONL', '21', 'OID', 'OAN', 'OPE',
    'OWH', 'ONP', 'OFR', 'ONAS'
]}

# Replace values in the specific column
df['Party'] = df['Party'].replace(replacements)

In [37]:
df.columns
df2 = df.groupby(["age_bracket", "Gender","Legislative", "Party"]).agg(Count=("FirstName", "count"), voted_2024 = ("11/05/2024-PG","count"),voted_2020 = ("11/03/2020-PG","count"),voted_2016 = ("11/08/2016-PG","count")).reset_index()

df3 = df.groupby(["age_bracket","Legislative", "Party"]).agg(Count=("FirstName", "count"), voted_2024 = ("11/05/2024-PG","count"),voted_2020 = ("11/03/2020-PG","count"),voted_2016 = ("11/08/2016-PG","count")).reset_index()

df3.head()

  age_bracket Legislative Party  Count  voted_2024  voted_2020  voted_2016
0       18-24          36   DEM    739         427         233           0
1       18-24          36   OTH     72          28           7           0
2       18-24          36   REP   1475         871         373           0
3       18-24          36   UNA   1123         440         174           0
4       18-24         01A   DEM    486         312         131           0

In [38]:
df3.to_csv('agg_MD_noGenderSplit.csv')

In [36]:
import pandas as pd
df2 = pd.read_csv("agg_MD.csv")
df2

,Unnamed: 0,age_bracket,Gender,Legislative,Party,Count,voted_2024,voted_2020,voted_2016
0,0,18-24,Female,36,DEM,454,274,151,0
1,1,18-24,Female,36,OTH,33,14,5,0
2,2,18-24,Female,36,REP,576,360,159,0
3,3,18-24,Female,36,UNA,568,227,87,0
4,4,18-24,Female,01A,DEM,308,202,73,0
...,...,...,...,...,...,...,...,...,...
2875,2875,65+,Male,47A,UNA,440,236,250,211
2876,2876,65+,Male,47B,DEM,1096,674,720,668
2877,2877,65+,Male,47B,OTH,65,23,24,25
2878,2878,65+,Male,47B,REP,158,95,97,93
2879,2879,65+,Male,47B,UNA,178,89,89,75